name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Newman Globally
        run: npm install -g newman@latest

      - name: Debug:Check Installed Global Packages
        run: npm list -g --depth=0

      - name: Debug:Show Global npm Path
        run: npm root -g

      - name: Install `htmlextra` Reporter Globally
        run: npm install -g newman-reporter-htmlextra@latest

      - name: Debug:Check Installed Global Packages Again
        run: npm list -g --depth=0

      - name: Debug:List Global Node Modules Directory
        run: ls -la $(npm root -g)

      - name: Debug:Check Where Newman & Reporters Are Installed
        run: which newman && which newman-reporter-htmlextra || true

      - name: Run Postman Collection
        run: newman run Kyla_Task.postman_collection.json -e Kyla_Task_env.postman_environment.json -r htmlextra,cli

      - name: Debug:List Generated Report Files
        run: ls -la newman || true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/*.html
